version: "3.7"

networks:
    officenet:
      external: true

services: 
    app:
        image: rohmanahmad/stok:1.0.0
        environment: 
            - REDIS_URI=redis://db2:6379/2
            - MONGO_URI=mongodb://db1:27017/stok
        ports:
            - 3001:3000
        working_dir: /app
        volumes: 
            - ./src:/app
        networks:
            - officenet
        command: node server.js
        external_links:
            - v403_mongodb_1:db1
            - redis_redis_1:db2