version: "3.7"

networks:
    officenet:
      external: true

services: 
    app:
        image: node:alpine
        environment: 
            - REDIS_URI="redis://redisdb:6379/2"
            - MONGO_URI="mongodb://mongod:27017/stok"
        ports:
            - 3001:3000
        working_dir: "/app"
        volumes: 
            - "./src:/app"
        networks:
            - officenet
        command: "node server.js"
        external_links:
            - v403_mongodb_1:mongod
            - redis_redis_1:redisdb